import Head from "next/head";
import { Navbar } from "../components/Navbar/Navbar";

// styles
import styles from "./index.module.scss";
export default function Home() {
  return (
    <div className={styles.content}>
      <Head>
        <title>E-commerce website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>
        <div className={styles.header}>
          <h1>Better clothing for the planet</h1>
          <p>
            Create screens directly in Method or add your images from Sketch or
            Figma. You can even sync designs from your cloud storage!
          </p>
          <div className={styles.button}>
            <p>Shop All</p>
          </div>
        </div>

        <div className={styles.image}></div>

        <div className={styles.ads}>
          <img src="images/ads.svg" />
        </div>
      </main>

      <footer></footer>
    </div>
  );
}
