import Head from "next/head";
import { useState } from "react";
import { Navbar } from "../components/Navbar/Navbar";
import { Home } from "../components/Home/Home";
import { Footer } from "../components/Footer/Footer";

// styles
import styles from "./index.module.scss";
export default function Index() {
  return (
    <div className={styles.content}>
      <Head>
        <title>E-commerce website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Home />
      <Footer />
    </div>
  );
}
